event_node:
  type: RedisEventNode
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  event_queue: ${NAME_PREFIX}_indexer
  hmac_key: ${INDEXER_HMAC_KEY}
  hmac_digest: sha512
  callback_workers: null
  mute_first_failed_connections: 10
  use_ssl: ${REDIS_SSL}
  log_errors: true

# base_url: http://pylon_main:8080

nltk_data: /data/cache/nltk

application_icon_path: /data/static/application_icon
application_tool_icon_path: /data/static/alita_static-main/tool_icons
default_entity_icons_path: /data/static/alita_static-main/default_entity_icons
