event_node:
  type: RedisEventNode
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}
  event_queue: ${NAME_PREFIX}_indexer
  hmac_key: ${INDEXER_HMAC_KEY}
  hmac_digest: sha512
  callback_workers: null
  mute_first_failed_connections: 10
  use_ssl: ${REDIS_SSL}
  log_errors: true

# base_url: http://pylon_main:8080

nltk_data: /data/cache/nltk

application_icon_path: /data/static/application_icon
application_tool_icon_path: /data/static/alita_static-main/tool_icons
default_entity_icons_path: /data/static/alita_static-main/default_entity_icons

auto_setup: true
ai_project_allowed_domains: "centry.user"
add_admin_roles:
  [
    "system",
    "admin",
    "editor",
    "viewer",
    "prompt_lib_public",
    "prompt_lib_moderators",
    "public_admin",
  ]

default_secret_keys:
  - auth_token
  - default_embedding_model_name
  - default_embedding_model_project_id
  - default_image_generation_model_name
  - default_image_generation_model_project_id
  - default_llm_high_tier_model_name
  - default_llm_high_tier_model_project_id
  - default_llm_low_tier_model_name
  - default_llm_low_tier_model_project_id
  - default_llm_mid_tier_model_name
  - default_llm_mid_tier_model_project_id
  - default_llm_model_name
  - default_llm_model_project_id
  - default_vectorstorage_model_name
  - default_vectorstorage_model_project_id
  - pgvector_project_connstr
  - pgvector_project_password
  - project_llm_key

default_release: ${ALITA_RELEASE}
auth_token: ${LICENSE_PASSWORD}

disable_monitoring_charts:
  - sentiment
  - relevancy
  - reliability
  - promptQuality
  - promptScatter
  - topicPrompt
  - topicChart
